keys:
  - &mateidibu_yubi_main age1yubikey1qtjzdmk9yse2hae6qd809qcetfhhnlhfxcclw3gmuhuasxnt5ww85tgwnfs
  - &mateidibu_yubi_backup age1yubikey1qg6rsxh03xunzgkh2mcj0uc3wvh9gasv8tqhvu2qszdxrr2qad7kzu38fvv
  - &rockpro64 age1ml0a7ktsaljw4cs2q0esqdhjkf3p33a4w2hv8j8eaw8r6w73rfqqhg7kqw
  - &rpi4 age14v3p705vkuuthxv9fgw8zfqrk0qcqhu6vz97en56nxzyh4u6j3zslesnuk
  - &vp4670 age12m9ucka7vvkz20q028lsr894mxq6gehq48d5ppkak2t75h7ltcjqt38rlp
  - &x570 age1ttzag9jjku50wrndj4wyy9030patpfn6rms9v5n8u7am2j73mvzqpz9eex
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *mateidibu_yubi_main
      - *mateidibu_yubi_backup
      - *rockpro64
      - *rpi4
      - *vp4670
      - *x570
