---
services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: 0:0
    network_mode: host
    volumes:
      - /containers/jellyfin/config:/config
      - /containers/jellyfin/cache:/cache
      - /containers/jellyfin/media:/media:ro
    restart: unless-stopped
