---
services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/Bucharest
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    volumes:
      - /containers/qbittorrent/config:/config
      - /containers/qbittorrent/downloads:/downloads
    network_mode: host
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
